version: '3.1'
services:
  couchbase-build:
    container_name: couchbase-build
    entrypoint: tail -f /dev/null
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    image: couchbasebuild/server-ubuntu18-build
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 8096:8096
      - 11207:11207
      - 11210:11210
      - 11211:11211
      - 18091:18091
      - 18092:18092
      - 18093:18093
      - 18094:18094
      - 18095:18095
      - 18096:18096
    volumes:
      - $HOME/.cbdepscache:/home/couchbase/.cbdepscache
      - $HOME:/mnt
      - $SSH_AUTH_SOCK:/ssh-agent
