version: '3.1'
services:
  couchbase-build:
    container_name: couchbase-build
    entrypoint: tail -f /dev/null
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    image: couchbasebuild/server-ubuntu18-build
    network_mode: "host"
    privileged: true
    volumes:
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - /home/couchbase:/home/couchbase
      - /home/james/Projects/couchbase-build:/home/couchbase/Projects/couchbase-build
      - /home/james/Projects/dotfiles:/home/couchbase/Projects/dotfiles
